### ISSUE TITLE
Boarding Container

### ISSUE THREAD

**Issue by Ploysth** [Ploysth/capstone_project#2]
# Value statement - a requirement, not a solution

As a user, I need a container with header and text
so that I can see my Boarding schedule
 
# Description (Design)

![Bildschirmfoto 2022-04-27 um 13 57 16](https://user-images.githubusercontent.com/100590395/165513142-8dd6b75f-62b8-423d-9d63-ef4b1a8cb35d.png)

the difference to #1 is the header and instead of check in gate number is written here.

The Boarding and Check In Cards are displayed one below each other (same page).

![Bildschirmfoto 2022-04-27 um 15 11 33](https://user-images.githubusercontent.com/100590395/165525632-08fe155b-2880-4f5c-ab94-702d64e88b4b.png)

**Comment by PReichetanz** [comment]
Do I see it right that the only difference to #1 (Check in Container) is the header text?
If so, you can reuse your component from there, yeah!

Where are the Boarding and Check In Cards displayed? Are there separate pages or are they displayed one below each other?

Regarding "Acceptance criteria" and Task, please refer to #1 and adjust the description here.
